version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: torgi_gov
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"